# Generated by Django 5.0.1 on 2024-01-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_feature_category_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="feature",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
