# Generated by Django 5.0.1 on 2024-01-25 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_feature_description_alter_feature_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="features",
            new_name="feature",
        ),
    ]
